# Generated by Django 5.1.7 on 2025-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('resume_file', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
    ]
