# Generated by Django 5.1.7 on 2025-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
